phpmyadmin: 
  environment:
   MYSQL_ROOT_PASSWORD: edureka
   MYSQL_USERNAME: root
  image: corbinu/docker-phpmyadmin
  links: 
    - "wordpress_db:mysql"
  ports: 
    - "8181:80"
wordpress: 
  image: wordpress
  links: 
    - "wordpress_db:mysql"
  ports: 
    - "8080:80"
wordpress_db: 
  environment:
   MYSQL_ROOT_PASSWORD: edureka
  image: mariadb
